/**
 * English Translations
 */

import { MarketingTranslations } from "./types";

export const en: MarketingTranslations = {
    // AI Language Instructions
    respondInLanguage: "Respond in English.",
    languageName: "English",

    // Report Headers
    executiveSummary: "Executive Summary",
    highlightsAndConcerns: "Highlights and Concerns",
    userAnalytics: "User Analytics",
    ratingsAndReviews: "Ratings and Reviews",
    improvementSuggestions: "Improvement Suggestions",
    competitivePositioning: "Competitive Positioning Analysis",
    marketOpportunityPriority: "Market Opportunity Priority Analysis",
    trendAnalysisAndPredictions: "Trend Analysis and Predictions",
    codebaseImprovements: "Codebase Improvement Suggestions",

    // Competitive Positioning
    marketPosition: "Market Position",
    competitorComparison: "Competitor Comparison",
    ourStrengths: "Our Strengths",
    ourWeaknesses: "Our Weaknesses",
    battleStrategy: "Battle Strategy",
    differentiationStrategy: "Differentiation Strategy",
    quickWins: "Quick Wins",

    // Market Opportunity
    prioritizedOpportunities: "Prioritized Opportunities",
    opportunity: "Opportunity",
    fitScore: "Fit Score",
    effort: "Effort",
    reason: "Reason",
    requiredChanges: "Required Changes",
    recommendedAction: "Recommended Action",
    strategicRecommendations: "Strategic Recommendations",

    // GitHub Improvements
    relatedFeature: "Related Feature",
    fileModifications: "File Modifications",
    expectedImpact: "Expected Impact",

    // Effort Levels
    low: "Low",
    medium: "Medium",
    high: "High",

    // Fit Scores
    excellent: "Excellent",
    good: "Good",
    moderate: "Moderate",
    poor: "Poor",

    // Misc
    continued: "(continued)",
    highlights: "Highlights",
    concerns: "Concerns",

    // Report metadata
    reportType: "Report Type",
    dailyReport: "Daily Report",
    weeklyReport: "Weekly Report",
    monthlyReport: "Monthly Report",
    period: "Period",
    generated: "Generated",
    dataSources: "Data Sources",
    aiAnalysis: "AI Analysis",

    // User Analytics
    activeUsers: "Active Users",
    sessionStatistics: "Session Statistics",
    avgSessionDuration: "Avg. Session Duration",
    sessionsPerUser: "Sessions per User",
    retention: "Retention",
    ageDemographics: "Age Demographics",
    countryDistribution: "Country Distribution",
    newUsers: "New Users",

    // Ratings & Reviews
    overallRatings: "Overall Ratings",
    platform: "Platform",
    rating: "Rating",
    totalRatings: "Total Ratings",
    ratingDistribution: "Rating Distribution",
    sentimentAnalysis: "Sentiment Analysis",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    commonThemes: "Common Themes",
    actionableInsights: "Actionable Insights",

    // Trend Analysis
    userGrowth: "User Growth",
    engagement: "Engagement",
    ratings: "Ratings",
    predictions: "Predictions",

    // Table Headers
    metric: "Metric",
    value: "Value",
    trend: "Trend",
    percentage: "Percentage",

    // Code modification types
    add: "Add",
    modify: "Modify",
    refactor: "Refactor",
    optimize: "Optimize",
    current: "Current",
    proposed: "Proposed",
    file: "File",
    type: "Type",

    // PDF specific
    pageOf: "Page {current} of {total}",
    generatedBy: "Generated by Masamune Marketing Workflow",

    // Repository info
    repository: "Repository",
    framework: "Framework",
};
