/**
 * GitHub Repository Analysis Data Types
 *
 * GitHubリポジトリ解析用のデータ型。
 */

/**
 * Configuration for GitHub Content Client.
 *
 * GitHubコンテンツクライアントの設定。
 */
export interface GitHubContentClientConfig {
    /** GitHub Personal Access Token */
    token: string;
    /** Repository in format "owner/repo" */
    repo: string;
}

/**
 * GitHub content item (file or directory).
 *
 * GitHubコンテンツアイテム（ファイルまたはディレクトリ）。
 */
export interface GitHubContentItem {
    name: string;
    path: string;
    sha: string;
    size: number;
    type: "file" | "dir" | "submodule" | "symlink";
    url: string;
    downloadUrl?: string;
}

/**
 * GitHub tree item from recursive tree API.
 *
 * 再帰ツリーAPIからのGitHubツリーアイテム。
 */
export interface GitHubTreeItem {
    path: string;
    mode: string;
    type: "blob" | "tree";
    sha: string;
    size?: number;
    url: string;
}

/**
 * Framework information detected from repository.
 *
 * リポジトリから検出されたフレームワーク情報。
 */
export interface FrameworkInfo {
    /** Framework name (flutter, nodejs, python, etc.) */
    framework: string;
    /** Available platforms */
    platforms: string[];
    /** Configuration file path */
    configFile?: string;
    /** Configuration file content */
    configContent?: string;
}

/**
 * File summary generated by AI.
 *
 * AIによって生成されたファイル要約。
 */
export interface FileSummary {
    /** File path in repository */
    path: string;
    /** Programming language */
    language?: string;
    /** Brief summary of the file */
    summary: string;
    /** Features/functionality provided by this file */
    features?: string[];
    /** Exported classes/functions */
    exports?: string[];
    /** When this summary was generated */
    analyzedAt: Date;
}

/**
 * Folder summary generated by aggregating file summaries.
 *
 * ファイル要約を集約して生成されたフォルダ要約。
 */
export interface FolderSummary {
    /** Folder path in repository */
    path: string;
    /** Brief summary of the folder's purpose */
    summary: string;
    /** Features/functionality provided by files in this folder */
    features: string[];
    /** Number of files in this folder */
    fileCount: number;
    /** When this summary was generated */
    analyzedAt: Date;
}

/**
 * Feature detail in final analysis.
 *
 * 最終解析における機能詳細。
 */
export interface FeatureDetail {
    /** Feature name */
    name: string;
    /** Feature description */
    description: string;
    /** Related file paths */
    relatedFiles: string[];
}

/**
 * Final GitHub repository analysis result.
 *
 * GitHubリポジトリ解析の最終結果。
 */
export interface GitHubRepositoryAnalysis {
    /** Repository full name (owner/repo) */
    repository: string;
    /** Analyzed path within repository */
    analyzedPath: string;
    /** Detected framework */
    framework: string;
    /** Available platforms */
    platforms: string[];
    /** Overall application/service overview */
    overview: string;
    /** Detailed feature list */
    features: FeatureDetail[];
    /** Architecture overview */
    architecture: string;
    /** Main dependencies */
    dependencies: string[];
    /** API endpoints (if applicable) */
    apiEndpoints?: string[];
    /** When analysis was completed */
    analyzedAt: string;
}

/**
 * Folder batch for processing.
 *
 * 処理用のフォルダバッチ。
 */
export interface FolderBatch {
    /** Folder path */
    folderPath: string;
    /** Files in this folder */
    files: string[];
}

/**
 * Processing state stored in Firestore.
 *
 * Firestoreに保存される処理状態。
 */
export interface GitHubAnalysisState {
    /** Current processing phase */
    phase: "init" | "processing" | "summarizing" | "completed" | "failed";
    /** Repository being analyzed */
    repository: string;
    /** Path within repository */
    repositoryPath: string;
    /** Detected framework info */
    framework?: FrameworkInfo;
    /** Total number of files to process */
    totalFiles: number;
    /** Number of files processed so far */
    processedFiles: number;
    /** List of all file paths to process */
    filePaths: string[];
    /** List of folder paths */
    folderPaths: string[];
    /** Folder batches for processing (one batch = one AI call) */
    folderBatches?: FolderBatch[];
    /** Current batch index (for tracking progress) */
    currentBatchIndex: number;
    /** Files per batch (legacy, not used in folder-based batching) */
    batchSize: number;
    /** Error message if failed */
    error?: string;
    /** When state was last updated */
    updatedAt: Date;
}

/**
 * File cache entry in Firestore.
 *
 * Firestoreのファイルキャッシュエントリ。
 */
export interface GitHubFileCacheEntry {
    /** File path */
    path: string;
    /** File type */
    type: "file";
    /** Programming language */
    language?: string;
    /** Summary of the file */
    summary: string;
    /** Features in this file */
    features?: string[];
    /** When analyzed */
    analyzedAt: Date;
}

/**
 * Folder cache entry in Firestore.
 *
 * Firestoreのフォルダキャッシュエントリ。
 */
export interface GitHubFolderCacheEntry {
    /** Folder path */
    path: string;
    /** Folder type */
    type: "folder";
    /** Summary of the folder */
    summary: string;
    /** Features in this folder */
    features: string[];
    /** Number of files */
    fileCount: number;
    /** When analyzed */
    analyzedAt: Date;
}

/**
 * GitHub analysis action command.
 *
 * GitHub解析アクションコマンド。
 */
export interface GitHubAnalysisActionCommand {
    /** Command name */
    command: "analyze_github_init" | "analyze_github_process" | "analyze_github_summary";
    /** Action index */
    index: number;
    /** Repository to analyze (owner/repo format) */
    githubRepository: string;
    /** Path within repository for monorepo support */
    githubRepositoryPath?: string;
}

/**
 * Excluded paths and patterns for file filtering.
 *
 * ファイルフィルタリング用の除外パスとパターン。
 */
export const EXCLUDED_PATHS = [
    ".git",
    "node_modules",
    ".dart_tool",
    "build",
    "dist",
    ".gradle",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    "venv",
    ".env",
    "coverage",
    ".nyc_output",
];

/**
 * Excluded file patterns (glob-like).
 *
 * 除外ファイルパターン。
 */
export const EXCLUDED_PATTERNS = [
    /\.lock$/,
    /\.env(\..+)?$/,
    /\.log$/,
    /\.min\.(js|css)$/,
    /\.map$/,
    /\.d\.ts$/,
    /\.generated\./,
    /\.g\.dart$/,
    /\.freezed\.dart$/,
];

/**
 * Binary file extensions to exclude.
 *
 * 除外するバイナリファイル拡張子。
 */
export const BINARY_EXTENSIONS = [
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".svg",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".zip", ".tar", ".gz", ".rar", ".7z",
    ".exe", ".dll", ".so", ".dylib",
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".mp3", ".mp4", ".wav", ".avi", ".mov", ".wmv",
    ".sqlite", ".db",
];

/**
 * Source code extensions for language detection.
 *
 * 言語検出用のソースコード拡張子。
 */
export const LANGUAGE_EXTENSIONS: Record<string, string> = {
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".dart": "Dart",
    ".py": "Python",
    ".rs": "Rust",
    ".go": "Go",
    ".java": "Java",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".cpp": "C++",
    ".c": "C",
    ".h": "C/C++ Header",
    ".hpp": "C++ Header",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".json": "JSON",
    ".xml": "XML",
    ".html": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".less": "LESS",
    ".md": "Markdown",
    ".sql": "SQL",
    ".sh": "Shell",
    ".bash": "Bash",
    ".zsh": "Zsh",
    ".gradle": "Gradle",
};
