import * as masamune from "@mathrunet/masamune";

/**
 * Define a list of applicable Functions for FirebaseFunctions.
 * 
 * FirebaseFunctions用の適用可能なFunctionの一覧を定義します。
 */
export const Functions = {
  /** 
   * Obtain an Agora.io security token.
   * 
   * Agora.ioのセキュリティトークンを取得します。
   */
  agoraToken: (options: masamune.HttpFunctionsOptions = {}) => new masamune.FunctionsData({ id: "agora_token", func: require("./functions/agora_token"), options: options }),
  /**
   * Convert files generated by Agora.io's cloud recording into an easy-to-handle format from within the app.
   * 
   * It is executed when the file is saved to FirebaseStorage.
   * 
   * Agora.ioのクラウドレコーディングで生成されたファイルをアプリ上から扱いやすい形式に変換します。
   * 
   * FirebaseStorageにファイルが保存されたタイミングで実行されます。
   */
  agoraCloudRecording: (options: masamune.StorageFunctionsOptions = {}) => new masamune.FunctionsData({ id: "agora_cloud_recording", func: require("./functions/agora_cloud_recording"), options: options }),
} as const;
