import * as data from "./lib/functions_data";

/**
 * Define a list of applicable Functions for FirebaseFunctions.
 * 
 * FirebaseFunctions用の適用可能なFunctionの一覧を定義します。
 */
export const Functions = {
  /** 
   * Function for sending PUSH notifications.
   * 
   * PUSH通知を送信するためのFunction。
   */
  sendNotification: new data.FunctionsData("send_notification", require("./functions/send_notification")),
  /** 
   * The text is generated using Open AI's GPT.
   * 
   * Open AIのChat GPTを利用して文章を生成します。
   */
  openAIChatGPT: new data.FunctionsData("openai_chat_gpt", require("./functions/openai_chat_gpt")),
  /** 
   * Obtain an Agora.io security token.
   * 
   * Agora.ioのセキュリティトークンを取得します。
   */
  agoraToken: new data.FunctionsData("agora_token", require("./functions/agora_token")),
  /**
   * Convert files generated by Agora.io's cloud recording into an easy-to-handle format from within the app.
   * 
   * It is executed when the file is saved to FirebaseStorage.
   * 
   * Agora.ioのクラウドレコーディングで生成されたファイルをアプリ上から扱いやすい形式に変換します。
   * 
   * FirebaseStorageにファイルが保存されたタイミングで実行されます。
   */
  agoraCloudRecording: new data.FunctionsData("agora_cloud_recording", require("./functions/agora_cloud_recording")),
  /**
   * Performs various Stripe processes.
   * 
   * Firestore integration is a must; please make Firestore available as well.
   *
   * Stripeの各種処理を実行します。
   * 
   * Firestoreとの連携が必須です。Firestoreも利用可能にしてください。
   */
  stripe: new data.FunctionsData("stripe", require("./functions/stripe")),
  /**
   * Receives and processes webhooks from Stripe.
   * 
   * Please register the URL when you deploy this in your Stripe webhook settings.
   * 
   * Firestore integration is a must; please make Firestore available as well.
   *
   * StripeからのWebhookを受け取り処理を行います。
   * 
   * こちらをデプロイした際のURLをStripeのWebhook設定に登録してください。
   * 
   * Firestoreとの連携が必須です。Firestoreも利用可能にしてください。
   */
  stripe_hook: new data.FunctionsData("stripe_hook", require("./functions/stripe_hook")),
  /**
   * Receive and process webhooks for Stripe Connect.
   * 
   * If you do not use Stripe Connect, do not configure it as a Webhook.
   * 
   * Please register the URL when you deploy this in your Stripe webhook settings.
   * 
   * Firestore integration is a must; please make Firestore available as well.
   *
   * Stripe Connect用のWebhookを受信して処理します。
   * 
   * Stripe Connectを利用しない場合はWebhookとして設定しないでください。
   * 
   * こちらをデプロイした際のURLをStripeのWebhook設定に登録してください。
   * 
   * Firestoreとの連携が必須です。Firestoreも利用可能にしてください。
   */
  stripe_hook_connect: new data.FunctionsData("stripe_hook_connect", require("./functions/stripe_hook_connect")),
  /**
   * Webhook for proper redirection when 3D Secure authentication is required.
   * 
   * It is used by accessing the URL directly.
   * 
   * Please set here for [returnUrl].
   *
   * 3Dセキュア認証が必要な場合、適切なリダイレクトを行うためのWebhookです。
   * 
   * 直接URLにアクセスすることで利用します。
   * 
   * [returnUrl]にこちらを設定してください。
   */
  stripe_hook_secure: new data.FunctionsData("stripe_hook_secure", require("./functions/stripe_hook_secure")),
} as const;
